version: '3.8'

services:
  web:
    build: .
    container_name: shop-smart-web
    ports:
      - "80:80"
    networks:
      - shopnet
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: shop-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: website
      MYSQL_PASSWORD: tartans@1
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql 
    networks:
      - shopnet

volumes:
  db_data:

networks:
  shopnet:
